api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    # formats:
    #     json: ['application/json']
    #     jsonld: ['application/json+ld']
    #     html: ['text/html']
    #     multipart: ['multipart/form-data']
    # resources:
    #     App\Entity\AirDrop:
    #         normalizationContext:
    #             groups: ['read']
    #         denormalizationContext:
    #             groups: ['write']
