api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            # max_age: 0
            # shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    # eager_loading:
    #     force_eager: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']    
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header    
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']