api_platform:
    title: Hello API Platform
    version: 1.0.0
    # http_cache:
    #     invalidation:
    #         enabled: true
    #         varnish_urls: ['%env(VARNISH_URL)%']
    #     public: true
    defaults:
        stateless: true
        cache_headers:
            # max_age: 0
            # shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']    
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header    
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    patch_formats:
        # mime_types: ['multipart/form-data']
        json: ['application/merge-patch+json']   