vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
 
    mappings:
        user:
            uri_prefix: /user/pict
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        coverPict:
            uri_prefix: /collection/cover
            upload_destination: '%kernel.project_dir%/public/images/collections/CoverPict'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        avatarPict:
            uri_prefix: /collection/avatar
            upload_destination: '%kernel.project_dir%/public/images/collections/avatarPict'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        airDropPict:
            uri_prefix: /airDrop/pict
            upload_destination: '%kernel.project_dir%/public/images/airDrops'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        nft:
            uri_prefix: /nft/pict
            upload_destination: '%kernel.project_dir%/public/images/nfts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer